// <auto-generated />
using System;
using Dotnetstore.WebAPI.Intranet.Entity.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Dotnetstore.WebAPI.Intranet.Entity.Migrations
{
    [DbContext(typeof(IntranetContext))]
    [Migration("20220903195025_v001")]
    partial class v001
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Dotnetstore.WebAPI.Intranet.Entity.Business.BusinessEntity", b =>
                {
                    b.Property<Guid?>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CreatedByID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("CreatedTime")
                        .IsRequired()
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("DeletedByID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("DeletedTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool?>("IsDead")
                        .IsRequired()
                        .HasColumnType("bit");

                    b.Property<bool?>("IsDeleted")
                        .IsRequired()
                        .HasColumnType("bit");

                    b.Property<bool?>("IsGDPR")
                        .IsRequired()
                        .HasColumnType("bit");

                    b.Property<bool?>("IsPublic")
                        .IsRequired()
                        .HasColumnType("bit");

                    b.Property<bool?>("IsSystem")
                        .IsRequired()
                        .HasColumnType("bit");

                    b.Property<bool?>("IsUpdated")
                        .IsRequired()
                        .HasColumnType("bit");

                    b.Property<bool?>("IsVisible")
                        .HasColumnType("bit");

                    b.Property<Guid?>("LastUpdatedByID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("LastUpdatedTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("ID");

                    b.HasIndex("ID")
                        .IsUnique();

                    b.ToTable("BusinessEntity", "Business");
                });

            modelBuilder.Entity("Dotnetstore.WebAPI.Intranet.Entity.Business.Store", b =>
                {
                    b.Property<Guid?>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CorporateID")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid?>("CreatedByID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("CreatedTime")
                        .IsRequired()
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("DeletedByID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("DeletedTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<bool?>("IsDead")
                        .IsRequired()
                        .HasColumnType("bit");

                    b.Property<bool?>("IsDeleted")
                        .IsRequired()
                        .HasColumnType("bit");

                    b.Property<bool?>("IsGDPR")
                        .IsRequired()
                        .HasColumnType("bit");

                    b.Property<bool?>("IsOwnStore")
                        .IsRequired()
                        .HasColumnType("bit");

                    b.Property<bool?>("IsPublic")
                        .IsRequired()
                        .HasColumnType("bit");

                    b.Property<bool?>("IsSystem")
                        .IsRequired()
                        .HasColumnType("bit");

                    b.Property<bool?>("IsUpdated")
                        .IsRequired()
                        .HasColumnType("bit");

                    b.Property<bool?>("IsVisible")
                        .HasColumnType("bit");

                    b.Property<Guid?>("LastUpdatedByID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("LastUpdatedTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("ID");

                    b.HasIndex("ID")
                        .IsUnique();

                    b.HasIndex("Name");

                    b.ToTable("Store", "Business");
                });
#pragma warning restore 612, 618
        }
    }
}
